build: Update pubspec.yaml and bump version
famedly/flutter_openssl_crypto pull request #2
Opened 2023-11-17 08:10 UTC by krille-chan

2023-11-17 08:59 UTC, coder-with-a-bushido approved these changes

2023-11-17 09:46 UTC, techno-disaster requested changes

2023-11-17 09:46 UTC, techno-disaster commented on .github/workflows/publish.yml
> +    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
You want to use our template here https://github.com/famedly/matrix-dart-sdk/blob/main/.github/workflows/publish.yml

also please setup the `pub.dev` env in github settings

2023-11-20 15:30 UTC, techno-disaster approved these changes

2023-11-20 15:31 UTC, merged